#!/bin/sh

/usr/sbin/logrotate  /opt/kaspersky/kuma/core/logrotate/stderr-logrotate.conf
EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t logrotate "kuma core stderr logrotate exited abnormally with [$EXITVALUE]"
fi
exit $EXITVALUE