# config file version
apiVersion: 1

datasources:
 - name: Prometheus
   type: prometheus
   access: proxy
   orgId: 1
   url: http://kuma-victoria-01:9090
   isDefault: true
   version: 1
   editable: true
   jsonData:
     httpMethod: "GET"
     timeInterval: 5s
